### ISSUE TITLE
Issues with importing hybris 1905 project

### ISSUE THREAD

**Issue by mikolayek** [SAP/hybris-commerce-eclipse-plugin#34]
** Content copied from eclipse marketplace website **

Can't import hybris 1905 project

Submitted by Andrei Osipenko on Fri, 2019-06-28 06:38

1) Installed fresh eclipse j2ee package.
2) Downloaded SAP Hybris Commerce Development Tools
3) Click import project / Import hybris extensions
4) selected localextensions.xml from hybris 1905 project
5) see error:
   Failed to import with error (put your mouse here to see more details): javax/xml/bind/JAXB

Environment:
Ubuntu 18.04.2 LTS
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

**Comment by mikolayek** [comment]
Issue checked on linux ubuntu 19.04 

!SESSION 2019-07-09 16:32:55.134 -----------------------------------------------
eclipse.buildId=4.12.0.I20190605-1800
java.version=11.0.3
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

that is eclipse 2019-06 version. tried to import vanilla accelerator created from Recipe "sap_aom_som_b2b_b2c"

project imported successfully.

if that issue occurs, please send eclipse workspace ".log" with import process

**Comment by frankzhy** [comment]
I also have such problem, could you let me know how to solve it ?
eclipse version: 4.14.0
java version 11.0.6

**Comment by mikolayek** [comment]
@frankzhy could you do 2 things, please?
first, can you download plugin source code, build extension by yourself (more info in README.md that is just maven execution) and re-check, please?
That issue has been fixed already. I am just in progress with another issue to deliver, then I will release new version.

Best,
Pawel

**Comment by chandnigideon** [comment]
@mikolayek : I am facing the same issue and I just installed Hybris 1905 with sapmachine-jdk-11.0.6.0.1.jdk, Eclipse 2019-12
I am also not able to import extensions.

**Comment by mikolayek** [comment]
Could you provide .log and eclipse plugin version please?

**Comment by namameht** [comment]
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.tryToRunProjectBuildAnalyzing(HybrisProjectsImportWizardPage.java:266)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.updateProjectList(HybrisProjectsImportWizardPage.java:253)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.handleBrowseDirectoryButtonPressed(HybrisProjectsImportWizardPage.java:242)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.access$1(HybrisProjectsImportWizardPage.java:237)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage$2.widgetSelected(HybrisProjectsImportWizardPage.java:153)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:151)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:280)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:142)
	at org.eclipse.ui.internal.actions.CommandAction.run(CommandAction.java:152)
	at org.eclipse.ui.actions.ImportResourcesAction.run(ImportResourcesAction.java:100)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:171)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.openWizardDialog(AbstractMarketplaceWizardCommand.java:146)
	at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.execute(AbstractMarketplaceWizardCommand.java:73)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXB
	at com.epam.yplugin.extensionloader.ProjectRecord.unmarshallExtensionInfo(ProjectRecord.java:106)
	at com.epam.yplugin.extensionloader.ProjectRecord.parseInfoFromFileInConstructor(ProjectRecord.java:35)
	at com.epam.yplugin.extensionloader.HierarchicalElement.<init>(HierarchicalElement.java:26)
	at com.epam.yplugin.extensionloader.HierarchicalElement.<init>(HierarchicalElement.java:22)
	at com.epam.yplugin.extensionloader.ProjectRecord.<init>(ProjectRecord.java:28)
	at com.epam.yplugin.extensionloader.ProjectFinderStrategy$ProjectFinderByDirectoryStrategy.createRecord(ProjectFinderStrategy.java:65)
	at com.epam.yplugin.extensionloader.ProjectFinderStrategy$ProjectFinderByDirectoryStrategy.getProjectRecords(ProjectFinderStrategy.java:58)
	at com.epam.yplugin.extensionloader.ProjectsFinder.run(ProjectsFinder.java:29)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXB cannot be found by com.epam.yplugin_2.0.4
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 9 more
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.tryToRunProjectBuildAnalyzing(HybrisProjectsImportWizardPage.java:266)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.updateProjectList(HybrisProjectsImportWizardPage.java:253)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.handleBrowseLocalextensionsButtonPressed(HybrisProjectsImportWizardPage.java:234)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.access$0(HybrisProjectsImportWizardPage.java:227)
	at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage$1.widgetSelected(HybrisProjectsImportWizardPage.java:147)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.ui.internal.handlers.WizardHandler$Import.executeHandler(WizardHandler.java:151)
	at org.eclipse.ui.internal.handlers.WizardHandler.execute(WizardHandler.java:280)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
	at org.eclipse.ui.internal.actions.CommandAction.runWithEvent(CommandAction.java:142)
	at org.eclipse.ui.internal.actions.CommandAction.run(CommandAction.java:152)
	at org.eclipse.ui.actions.ImportResourcesAction.run(ImportResourcesAction.java:100)
	at org.eclipse.ui.actions.BaseSelectionListenerAction.runWithEvent(BaseSelectionListenerAction.java:171)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.openWizardDialog(AbstractMarketplaceWizardCommand.java:146)
	at org.eclipse.epp.internal.mpc.ui.commands.AbstractMarketplaceWizardCommand.execute(AbstractMarketplaceWizardCommand.java:73)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4955)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4448)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXB
	at com.epam.yplugin.extensionloader.HybrisProjectsBuildAnalyzer.unmarshallLocalExtensionFile(HybrisProjectsBuildAnalyzer.java:151)
	at com.epam.yplugin.extensionloader.HybrisProjectsBuildAnalyzer.getProjectRecords(HybrisProjectsBuildAnalyzer.java:45)
	at com.epam.yplugin.extensionloader.ProjectFinderStrategy$ProjectFinderByLocalextensionsXmlStrategy.getProjectRecords(ProjectFinderStrategy.java:82)
	at com.epam.yplugin.extensionloader.ProjectsFinder.run(ProjectsFinder.java:29)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by namameht** [comment]
This is the error I get while importing the extensions

**Comment by mikolayek** [comment]
@namameht sorry, but that stacktrace is useless. it is related to different plugin. You are using plugin from EPAM, not SAP. Take a look at namespace `com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage` 

```
com.epam.yplugin.extensionloader.ProjectRecord.unmarshallExtensionInfo(ProjectRecord.java:106)
at com.epam.yplugin.extensionloader.ProjectRecord.parseInfoFromFileInConstructor(ProjectRecord.java:35)
at com.epam.yplugin.extensionloader.HierarchicalElement.(HierarchicalElement.java:26)
at com.epam.yplugin.extensionloader.HierarchicalElement.(HierarchicalElement.java:22)
at com.epam.yplugin.extensionloader.ProjectRecord.(ProjectRecord.java:28)
at com.epam.yplugin.extensionloader.ProjectFinderStrategy$ProjectFinderByDirectoryStrategy.createRecord(ProjectFinderStrategy.java:65)
at com.epam.yplugin.extensionloader.ProjectFinderStrategy$ProjectFinderByDirectoryStrategy.getProjectRecords(ProjectFinderStrategy.java:58)
at com.epam.yplugin.extensionloader.ProjectsFinder.run(ProjectsFinder.java:29)
at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXB cannot be found by com.epam.yplugin_2.0.4
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
... 9 more
java.lang.reflect.InvocationTargetException
at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:397)
at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1033)
at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.tryToRunProjectBuildAnalyzing(HybrisProjectsImportWizardPage.java:266)
at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.updateProjectList(HybrisProjectsImportWizardPage.java:253)
at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.handleBrowseLocalextensionsButtonPressed(HybrisProjectsImportWizardPage.java:234)
at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage.access$0(HybrisProjectsImportWizardPage.java:227)
at com.epam.yplugin.extensionloader.wizards.HybrisProjectsImportWizardPage$1.widgetSelected(HybrisProjectsImportWizardPage.java:147)
```
