### ISSUE TITLE
Not compatible with Java 11?

### ISSUE THREAD

**Issue by christian-ertl** [SAP/hybris-commerce-eclipse-plugin#36]
`!MESSAGE Errors running builder 'TSV Validation Project Builder' on project 'webservicescommons'.
!STACK 0
com.hybris.ps.tsv.exceptions.RuleException: Unmarshalling problem
        at com.hybris.ps.tsv.services.impl.DefaultRuleService.loadRulesFromStream(DefaultRuleService.java:77)
        at com.hybris.ps.tsv.services.impl.DefaultRuleService.loadDefaultRules(DefaultRuleService.java:47)
        at com.hybris.hyeclipse.tsv.builder.StandardTsvBuilder.getValidator(StandardTsvBuilder.java:34)
        at com.hybris.hyeclipse.tsv.builder.TsvBuilder.checkTsv(TsvBuilder.java:93)
        at com.hybris.hyeclipse.tsv.builder.TsvBuilder.fullBuild(TsvBuilder.java:135)
        at com.hybris.hyeclipse.tsv.builder.TsvBuilder.build(TsvBuilder.java:72)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:833)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
        at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:504)
        at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:404)
        at com.hybris.yps.hyeclipse.handlers.EclipseRefreshAndBuildHandler.refreshAndFullBuild(EclipseRefreshAndBuildHandler.java:91)
        at com.hybris.yps.hyeclipse.handlers.EclipseRefreshAndBuildHandler.access$0(EclipseRefreshAndBuildHandler.java:67)
        at com.hybris.yps.hyeclipse.handlers.EclipseRefreshAndBuildHandler$1.run(EclipseRefreshAndBuildHandler.java:51)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: javax.xml.bind.JAXBException: Provider com.sun.xml.bind.v2.ContextFactory not found
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:152)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:299)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:372)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:337)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:244)
        at com.hybris.ps.tsv.services.impl.DefaultRuleService.getJaxbContext(DefaultRuleService.java:126)
        at com.hybris.ps.tsv.services.impl.DefaultRuleService.getUnmarshaller(DefaultRuleService.java:137)
        at com.hybris.ps.tsv.services.impl.DefaultRuleService.loadRulesFromStream(DefaultRuleService.java:69)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.eclipse.osgi.internal.framework.ContextFinder.loadClass(ContextFinder.java:139)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:117)
        ... 27 more
`

**Comment by mikolayek** [comment]
Thanks for raising an issue. will take a look at issue.

Thanks,
Pawel

**Comment by redsnake1987** [comment]
@mikolayek The problem is in: hybris-commerce-eclipse-plugin-master\com.hybris.hyeclipse.tsv.extended\lib\tsv-extended-0.0.1-SNAPSHOT.jar within the class com.hybris.ps.tsv.extended.utils.ClassPathUtils --> Line 21 (URLClassLoader)ClassLoader.getSystemClassLoader(); is not returning a URLClassLoader since JDK 9+. A nice solution is mentioned here: https://stackoverflow.com/a/51584718

**Comment by mikolayek** [comment]
Thanks for bringing it up. I will fix it next week.

Cheers,
Pawel

**Comment by mikolayek** [comment]
eclipse.buildId=4.10.0.I20181206-0815
java.version=11.0.3
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_PL
Framework arguments:  -product org.eclipse.epp.package.java.product -product org.eclipse.epp.package.java.product -keyring /Users/i303764/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.java.product -data file:/Users/i303764/hy400-training/ -product org.eclipse.epp.package.java.product -keyring /Users/i303764/.eclipse_keyring

org.eclipse.e4.ui.workbench
Error
Thu Feb 06 09:28:55 CET 2020
Command 'com.hybris.hyeclipse.tsvextended.commands.tsvCommand' failed

org.eclipse.core.commands.ExecutionException: Error executing 'com.hybris.hyeclipse.tsvextended.commands.tsvCommand': java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4143)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3760)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
	... 35 more
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
	at com.hybris.hyeclipse.tsvextended.ui.TSVExtendedAnalyser.initData(TSVExtendedAnalyser.java:132)
	at com.hybris.hyeclipse.tsvextended.ui.TSVExtendedAnalyser.<init>(TSVExtendedAnalyser.java:68)
	at com.hybris.hyeclipse.tsvextended.ui.ModuleTableViewer.addChildControls(ModuleTableViewer.java:145)
	at com.hybris.hyeclipse.tsvextended.ui.ModuleTableViewer.<init>(ModuleTableViewer.java:41)
	at com.hybris.hyeclipse.tsvextended.platform.handlers.TSVExtendedHandler.run(TSVExtendedHandler.java:47)
	at com.hybris.hyeclipse.tsvextended.handlers.TSVExtendedHandlerWrapper.execute(TSVExtendedHandlerWrapper.java:33)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
	... 39 more
Caused by: java.lang.ExceptionInInitializerError
	at com.hybris.hyeclipse.tsvextended.ui.TSVExtendedAnalyser$1.run(TSVExtendedAnalyser.java:94)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.hybris.ps.tsv.extended.utils.ClassPathUtils.<clinit>(ClassPathUtils.java:21)
	... 2 more

**Comment by nalinikare** [comment]
Is this issue fixed?

**Comment by nalinikare** [comment]
Is this issue fixed?

**Comment by mikolayek** [comment]
no. not yet

**Comment by shiva1976** [comment]
When can we expect this to be fixed?

**Comment by mikolayek** [comment]
Right now I am fully busy with current project which is on Java8 and do not have spare time to fix that particular issue. It looks like I will be able to fix it in June. In June I have plan to review plugin with Commerce 2005 which has been recently released. 
But hey, I have good news. That’s open source. You have an access to code and can fix it by yourself. I will be more than happy to merge your pull request if you want to share with community.

All the best,
Pawel

**Comment by mikolayek** [comment]
It looks like I will be able to fix it in June. In June I have plan to review plugin with Commerce 2005 which has been recently released.
