### ISSUE TITLE
Error when Importing project

### ISSUE THREAD

**Issue by igna-davidboyd** [SAP/hybris-commerce-eclipse-plugin#48]
**Describe the bug**
Eclipse IDE for Enterprise Java Developers (includes Incubating components)
Version: 2020-06 (4.16.0)
Build id: 20200615-1200
OS: Mac OS X, v.10.15.6, x86_64 / cocoa
Java version: 11.0.1

Have done a fresh install of the plugin version 1.4.  When I go to import the platform I get the following error:  java.lang.NoClassDefFoundError:de/hybris/bootstrap/config/SystemConfig

I am working on V 2005 with Spartacus

**To Reproduce**
1. Go To File -> Import
2. Click on SAP Hybris [y] to expand it and then select Import SAP Hybris Platform
3. Modal is displayed
4. Navigate to the platform home folder which in my case is : ~/Development/project-xxx/xxx-spartacus/core-customize/hybris/bin/platform
5. Leave all Options and Tomcat settings as checked
6. Selected Finish
7. Existing projects are removed, and then get error modal as stated above.

**Expected behavior**
Expected for the proper extensions and needed dependencies to be loaded into the package explorer based off of the localextension.xml - like it use to do

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
OS: Mac OS X, v.10.15.6, x86_64 / cocoa
Java version: 11.0.1

**Additional context**

**Comment by igna-davidboyd** [comment]
So - existing workspace/project

Upgraded to 1.5, eclipse restarted

Selected to import project, selected the platform directory, all projects/extensions/packages deleted, then I get the following error message

Error occurred during importing project
Try to reproduce issue running "ant clean all" in termminal
More details in stack trace below

Reason
java.lang.NoClassDefFoundError: de/hybris/bootstrap/config/SystemConfig

**Comment by mikolayek** [comment]
Hm... I have unzipped fresh 2005 commerce version and used "cx" recipe to get default localextensions.xml.

I was able to import project with no error. I really do not know where the issue lays.

could you go to hybris/bin/platform and run in terminal "ant clean all"? do you get same issue, or it builds correctly?

could you provide ".log" file from your <workspace directory>/.metadata folder, please?

if you think that there are information that you would not like to share publicly, you can send me it via email which is my <first name>.<last name>[at]sap.com 
Thank you in advance.

Best,
Pawel

**Comment by igna-davidboyd** [comment]
It could be the way things are setup. 
So I am using 2005 patch 0
the project was created in the standard way, run the cx recipe and then do a modgen
When I do an ant clean all - no compile issues
We are using spartacus, again not sure if that is an issue or not
Folder structure is

<project_home>
 ->core-customize
-->hybris
---> standard folder structure here
-->installer
-> js-storefront

Now, we do have a custom installer that we are using, so this creates the local properties file as well as the local extensions

attaching the .log file


[david_boyd_eclipse_log_file.txt](https://github.com/SAP/hybris-commerce-eclipse-plugin/files/5211461/david_boyd_eclipse_log_file.txt)

**Comment by mikolayek** [comment]
Hello David, could you check import with my latest build which contains additional commit: https://github.com/mikolayek/hybris-commerce-eclipse-plugin/commit/f4783c745de73f6381576280353744a4b28741b6

To install in eclipse please follow steps:

Eclipse Menu:
- Help -> Install New Software...
- on modal window click on: [Add...] Button
- on new modal window click on [Archive...] Button
- select previously downloaded snapshot of version 1.5.1 attached to that message.
- follow eclipse installer steps
- remove all extensions and re-import again.

Thank you.
[com.hybris.hyeclipse.site-1.5.1-SNAPSHOT.zip](https://github.com/SAP/hybris-commerce-eclipse-plugin/files/5218051/com.hybris.hyeclipse.site-1.5.1-SNAPSHOT.zip)



Please find zip with plugin attached

**Comment by igna-davidboyd** [comment]
No change - same error.

I tried to import an 1811 project as well as a 2005 project.  Both failed.

Not sure as to what has occurred with this plugin.  It worked in the past and then there was some update that has caused it to fail.

Is it expecting a certain kind of commerce structure?  JVM version?

**Comment by mikolayek** [comment]
oh. Bummer.
Regarding JVM for Commerce and eclipse, there is only one condition. Eclipse has to run on same JVM version or newer than Commerce. If eclipse is running JVM11 you are on safe side. You will run all Commerce versions. More info here: 
https://github.com/SAP/hybris-commerce-eclipse-plugin/blob/master/docs/kb/info.md

So... regarding commerce structure, I test plugin with standard commerce platform, which is same since 4.6, which is the first version I have used 👍 
so.
./hybris/
./hybris/config
./hybris/bin/platform
./hybris/bin/custom

if you have any changes e.g. symlinks I am happy to get feedback.
For me that issue is strange. I haven't heard of that one before... plus. jar file with ybootstrap.jar is included in plugin, so class should be available... that is why I have created 1.5.1 change, to double-check if jar file is in plugin.

**Comment by igna-davidboyd** [comment]
So with 2005 we now have
./hybris/
./hybris/config
./hybris/bin
./hybris/bin/custom
./hybris/bin/modules
./hybris/bin/platform

For 1811
./hybris/bin
./hybris/bin/custom
./hybris/bin/platform
./hybris/bin/...< all the platform extensions >

I tried using SAP Machine V1.11 as well as Java 1.11 same issue in 2005

**Comment by skottska** [comment]
I had this error and I believe it is to do with having installed Eclipse in a directory whose path contains a space. When I moved my Eclipse install away from "Program Files" then it worked (using 1.5.5). This stacktrace appears right before the java.lang.NoClassDefFoundError:de/hybris/bootstrap/config/SystemConfig

> MESSAGE URISyntaxException | IOException
!STACK 0
java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/eclipse/eclipse-java-2020-09-R-win32-x86_64/eclipse/configuration/org.eclipse.osgi/518/0/.cp/ybootstrap/log4j-1.2.17.jar
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URL.toURI(URL.java:1036)
	at com.hybris.hyeclipse.ytypesystem.Activator.entryToFile(Activator.java:224)
	at com.hybris.hyeclipse.ytypesystem.Activator.loadBootstrapBundle(Activator.java:206)
	at com.hybris.hyeclipse.ytypesystem.Activator.start(Activator.java:110)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:814)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:806)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:763)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1011)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:506)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:572)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:473)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.hybris.yps.hyeclipse.Activator.getTypeSystemExporter(Activator.java:103)
	at com.hybris.yps.hyeclipse.Activator.resetPlatform(Activator.java:119)
	at com.hybris.yps.hyeclipse.utils.Importer.resetProjectsFromLocalExtensions(Importer.java:77)
	at com.hybris.yps.hyeclipse.wizards.ImportPlatformWizard.importPlatform(ImportPlatformWizard.java:294)
	at com.hybris.yps.hyeclipse.wizards.ImportPlatformWizard$1.run(ImportPlatformWizard.java:227)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

**Comment by mikolayek** [comment]
Hi @skottska , thank you for your analysis.

I will check it out today

Best,
Pawel

**Comment by mikolayek** [comment]
Hello @skottska thank you for a tip about white-space in file path. That helped with building reproducible test scenario.
Fix has been implemented and released in 1.5.5 version.

Thanks,
Pawel
